#!/bin/bash
# dump all files in bee_sort into a single lua file,
# so it can be more easily pasted into a computer

# should write to output/bee_sort.lua
output_file="output/bee_sort.lua"
mkdir -p "$(dirname "$output_file")"
echo "-- Bee Sort Lua Module" > "$output_file"
echo "-- Generated by compile.sh" >> "$output_file"
echo "" >> "$output_file"

# Function to append a file to the output file
append_file() {
    local file="$1"
    if [[ -f "$file" ]]; then
        echo "-- Contents of $file" >> "$output_file"
        cat "$file" >> "$output_file"
        echo "" >> "$output_file"
    else
        echo "Warning: $file does not exist, skipping."
    fi
}

# List of files to include in the output,
# in order of least dependencies to most
files=(
    "table_utils/table_utils.lua"
    "bee_sort/selectors.lua"
    "bee_sort/sort.lua"
    "bee_sort/controller.lua"
)

# Append each file to the output file
for file in "${files[@]}"; do
    append_file "$file"
done

# Need to comment out all lines beginning with "require"
sed -i 's/^\(require.*\)/-- \1/' "$output_file"

echo "Compilation complete."
