return {
  {
    mod_id = "minecraft",
    raw_name = "tile.obsidian",
    max_size = 64,
    max_dmg = 0,
    dmg = 0,
    qty = 64,
    id = "minecraft:obsidian",
    ore_dict = {
      obsidian = true,
      blockObsidian = true,
    },
    display_name = "Obsidian",
    name = "obsidian",
  },
  {
    mod_id = "minecraft",
    raw_name = "item.leather",
    max_size = 64,
    max_dmg = 0,
    dmg = 0,
    qty = 64,
    id = "minecraft:leather",
    ore_dict = {
      itemLeather = true,
    },
    display_name = "Leather",
    name = "leather",
  },
  {
    mod_id = "minecraft",
    raw_name = "item.ingotiron",
    max_size = 64,
    max_dmg = 0,
    dmg = 0,
    qty = 64,
    id = "minecraft:iron_ingot",
    ore_dict = {
      ingotIron = true,
    },
    display_name = "Iron Ingot",
    name = "iron_ingot",
  },
  {
    mod_id = "minecraft",
    raw_name = "item.dyepowder.blue",
    max_size = 64,
    max_dmg = 0,
    dmg = 4,
    qty = 64,
    id = "minecraft:dye",
    ore_dict = {
      cropLapender = true,
      dye = true,
      gemLapis = true,
      dyeBlue = true,
    },
    display_name = "Lapis Lazuli",
    name = "dye",
  },
  {
    mod_id = "minecraft",
    raw_name = "item.diamond",
    max_size = 64,
    max_dmg = 0,
    dmg = 0,
    qty = 64,
    id = "minecraft:diamond",
    ore_dict = {
      gemDiamond = true,
    },
    display_name = "Diamond",
    name = "diamond",
  },
  {
    display_name = "Oak Wood Planks",
    qty = 64,
    max_size = 64,
    max_dmg = 0,
    raw_name = "tile.wood.oak",
    burn_time = 300,
    id = "minecraft:planks",
    dmg = 0,
    ore_dict = {
      plankWood = true,
    },
    name = "planks",
    mod_id = "minecraft",
  },
  {
    mod_id = "minecraft",
    raw_name = "item.emerald",
    max_size = 64,
    max_dmg = 0,
    dmg = 0,
    qty = 64,
    id = "minecraft:emerald",
    ore_dict = {
      gemEmerald = true,
    },
    display_name = "Emerald",
    name = "emerald",
  },
  {
    mod_id = "minecraft",
    raw_name = "item.ingotgold",
    max_size = 64,
    max_dmg = 0,
    dmg = 0,
    qty = 64,
    id = "minecraft:gold_ingot",
    ore_dict = {
      ingotGold = true,
    },
    display_name = "Gold Ingot",
    name = "gold_ingot",
  },
  {
    mod_id = "minecraft",
    raw_name = "tile.stonebrick",
    max_size = 64,
    max_dmg = 0,
    dmg = 0,
    qty = 64,
    id = "minecraft:cobblestone",
    ore_dict = {
      cobblestone = true,
    },
    display_name = "Cobblestone",
    name = "cobblestone",
  },
}
